language: node_js
node_js:
  - "0.11"
  - "0.10"
services:
  - mongodb
before:
  - npm install -g istanbul
  - npm install -g mocha
after_success:
  - istanbul cover ./node_modules/.bin/_mocha -- -R spec test/Acceptance_Tests
  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
  - npm run report-coverage