language: node_js
node_js:
  - "0.11"
  - "0.10"
services:
  - mongodb
after:
  - istanbul cover ./node_modules/mocha/bin/_mocha --report lcovonly -- -R spec && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
  - npm run report-coverage