language: node_js
node_js:
  - "0.11"
  - "0.10"
services:
  - mongodb
after_success:
- ./node_modules/.bin/jscoverage lib lib-cov
- ./node_modules/.bin/mocha test -R mocha-lcov-reporter | ./node_modules/coveralls/bin/coveralls.js